<?php
$CONFIG = array (
  'instanceid' => 'oc5bygpiu2yx',
  'passwordsalt' => '+5lwpRznkgH8OWuiZV6FKiw6QW2z5u',
  'secret' => 'EtI9Efkr8LX8sf7CIGTFbmgLL0u/Cj1TvojQlr1ty3PUS2a/',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'alhasscloud.ddns.net',
    2 => '192.168.2.103',
    3 => 'alhasscloud.com',
  ),
  'datadirectory' => '/home/alhassane/Alhass/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '19.0.6.2',
  'overwrite.cli.url' => 'http://localhost/alhasscloud',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'alhassane',
  'dbpassword' => 'thecriminal440',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpmode' => 'sendmail',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 25,
  'mail_smtptimeout' => 10,
  'default_language' => 'fr_FR',
  'default_locale' => 'fr_FR',
  'maintenance' => false,
  'loglevel' => 2,
  'app_install_overwrite' => 
  array (
    0 => 'circles',
    1 => 'occweb',
    2 => 'preferred_providers',
    3 => 'socialsharing_email',
    4 => 'socialsharing_facebook',
    5 => 'breezedark',
  ),
  'theme' => '',
);
